# FlyFast
# 23.5.230515
#
# Usage
#   docker-compose build --no-cache
#   docker-compose up
#
#
# Example in Bash
#   export ATERNITY_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   export ATERNITY_CUSTOMER_ID="12341234-12341234-13241234"
#   export ALLUVIO_UJI_TAG="<script id=ALLUVIO-Aternity-UJI src=http:\/\/cdn\.riverbed\.com\/uji\.js><\/script>"
#   docker-compose up
#
# Example in PowerShell
#   $env:ATERNITY_SAAS_SERVER_HOST="agents.apm.myaccount.aternity.com"
#   $env:ATERNITY_CUSTOMER_ID="12341234-12341234-13241234"
#   $env:ALLUVIO_UJI_TAG="<script id=ALLUVIO-Aternity-UJI src=http:\/\/cdn\.riverbed\.com\/uji\.js><\/script>"
#   docker-compose up

version: '3.8'
services:

  apm-collector:
    image: registry.hub.docker.com/aternity/apm-collector:latest
    container_name: apm-collector
    environment:
      SERVER_URL: "wss://${ATERNITY_SAAS_SERVER_HOST}/?RPM_AGENT_CUSTOMER_ID=${ATERNITY_CUSTOMER_ID}"

  flyfast-flightsearch:
    build: ./FlyFast-FlightSearch
    depends_on:
      - apm-collector
    container_name: flyfast-flightsearch
    environment:
      COLLECTOR_URL: http://apm-collector:55681/v1/traces
    ports:
      - "8080:8080"

  flyfast-webui:
    build: ./FlyFast-WebUI
    depends_on:
      - flyfast-flightsearch
      - apm-collector
    container_name: flyfast-webui
    environment:
      REACT_APP_FLIGHT_SEARCH: http://flyfast-flightsearch:8080
      REACT_APP_OPENTELEMETRY_ENDPOINT: http://apm-collector:55681
      ALLUVIO_UJI_TAG: ${ALLUVIO_UJI_TAG}

    ports:
      - "80:80"